DROP DATABASE IF EXISTS ProyectoFinal;
CREATE DATABASE ProyectoFinal;
USE ProyectoFinal;

CREATE TABLE Usuario
(
    id INTEGER NOT NULL,
    email VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    usuario VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    contrasenna VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    nombre VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    apellidos VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    privada BOOLEAN NOT NULL,
    foto VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE Publicacion
(
    id INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    texto VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    foto VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE Solicitud
(
    id INTEGER NOT NULL,
    id_usuario1 INTEGER NOT NULL,
    id_usuario2 INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE Amistad
(
    id INTEGER NOT NULL,
    id_usuario1 INTEGER NOT NULL,
    id_usuario2 INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE Megusta
(
    id INTEGER NOT NULL,
    id_publicacion INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE Comentario
(
    id INTEGER NOT NULL,
    id_publicacion INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    comentario VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `Usuario`
    ADD PRIMARY KEY (`id`),
    ADD UNIQUE KEY `email` (`email`),
    ADD UNIQUE KEY `usuario` (`usuario`);
ALTER TABLE `Usuario`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `Publicacion`
    ADD PRIMARY KEY (`id`),
    ADD CONSTRAINT `PERTENECE_A` FOREIGN KEY (`id_usuario`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Publicacion`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `Solicitud`
    ADD PRIMARY KEY (`id`),
    ADD CONSTRAINT `ENVIADA_POR` FOREIGN KEY (`id_usuario1`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `RECIBIDA_POR` FOREIGN KEY (`id_usuario2`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Solicitud`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `Amistad`
    ADD PRIMARY KEY (`id`),
    ADD CONSTRAINT `SOLICITADA_POR` FOREIGN KEY (`id_usuario1`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `ACEPTADA_POR` FOREIGN KEY (`id_usuario2`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Amistad`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `Megusta`
    ADD PRIMARY KEY (`id`),
    ADD CONSTRAINT `PUBLICACION` FOREIGN KEY (`id_publicacion`) REFERENCES `Publicacion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `PULSADO_POR` FOREIGN KEY (`id_usuario`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Megusta`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `Comentario`
    ADD PRIMARY KEY (`id`),
    ADD CONSTRAINT `PUBLICADO_EN` FOREIGN KEY (`id_publicacion`) REFERENCES `Publicacion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `PUBLICADO_POR` FOREIGN KEY (`id_usuario`) REFERENCES `Usuario`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Comentario`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

INSERT INTO `usuario` (`id`, `email`, `usuario`, `contrasenna`, `nombre`, `apellidos`, `foto`) VALUES
(1, 'david@gmail.com', 'davidbm99', 'david1234', 'david', 'Bermejo Moreno', 'fotoPerfil.jpg');

